use_frameworks!

target 'AZWalkthrough_Example' do
  pod 'AZWalkthrough', :path => '../'

  target 'AZWalkthrough_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
